

//@ sourceMappingURL=system.map

c={D:function(a,b,d){d=void 0!=d&&1==d;!0!==a&&!0!==d||console.info(b);!0===d&&alert(b)},K:function(a,b){var d=a;if(a&&b){for(var e=0,f=b.length;e<f&&(d=d[b[e]],void 0!==d);e++);return d}}};c.PathObjectGet=c.K;c.ub=function(a,b,d){var e=a;if(a&&b){a=0;for(var f=b.length;a<f;a++){var h=b[a];if(a===b.length-1){e[h]=d;break}e=e[h];if(void 0===e)break}}};c.PathObjectSet=c.ub;c.R=function(a){for(var b=[],d=0,e=a.length;d<e;d++)b.push(a[d]);return b};
c.Ha=function(a){if(a instanceof Array){result=[];for(var b=0,d=a.length;b<d;b++)result[b]=c.Ha(a[b]);return result}if(a instanceof Object){result={};for(b in a)a.hasOwnProperty(b)&&(result[b]=c.Ha(a[b]));return copy}a instanceof Date&&c.D(!0,"instance of class Date in DeepClone");return a};c.Qa=function(a,b){for(var d="",e=a;0<e;--e)d+=b[Math.floor(Math.random()*b.length)];return d};c.RandomString=c.Qa;c.mb=function(a){return Array.isArray(a)};c.sd=function(a){return"[object Number]"===Object.prototype.toString.call(a)};c.c={};c.c.Ca="data";c.c.ba="op";
c.c.h={dd:"pushconst",Tc:"getstaticdataobject",vb:"getnode",wb:"setnode",Rc:"getdocumentvalue",fd:"setdocumentvalue",Sc:"getobjectvalue",gd:"setobjectvalue",$c:"objecthaskey",Zc:"objectaddkey",ad:"objectremovekey",bd:"objecttostack",ld:"stacktoobject",Hc:"dup",ed:"remove",Uc:"if",Vc:"ifexit",md:"testundefined",Gc:"clear",Ic:"equal",Xc:"lessequal",Wc:"less",Ec:"and",cd:"or",Yc:"not",Fc:"arraytostack",kd:"stacktoarray",hd:"stackalltrue",jd:"stackanytrue",Jc:"f0",Kc:"f1",Lc:"f2",Mc:"f3",Nc:"f4",Oc:"f5",
Pc:"f6",Qc:"f7"};c.c.L="value";c.c.Sa="node";c.c.B="type";c.c.g={ma:"bool",na:"boolarray",va:"int",wa:"intarray",qa:"float",ra:"floatarray",za:"string",Aa:"stringarray",xa:"key",ya:"keyarray",oa:"document",pa:"documentarray",ua:"iddocumentmap",sa:"hashset",ta:"hashsetarray",wd:"unknown",xd:"unknownarray"};c.cb={};
c.cb.Jb=function(a,b,d,e){c.D(!1,"DagNodeCalculateHelper.CalculateValue");a.length=0;for(var f=!0,h=0,m=b.length;h<m&&!0===f;h++){var k=b[h];if(!k)throw Error("null instruction at:"+h);var g=k[c.c.ba];switch(g){default:throw Error("invalid instruction at:"+h+" operation:"+g);case c.c.h.dd:g=k[c.c.L];a.push(g);break;case c.c.h.Tc:var k=a.pop(),l=c.K(d,k);a.push(l);break;case c.c.h.vb:k=k[c.c.Sa];g=k.J();a.push(g);break;case c.c.h.wb:g=a.pop();k=k[c.c.Sa];k.P(g);break;case c.c.h.Rc:k=a.pop();if(0==
("string"===typeof k||k instanceof String))throw Error("GetDocumentValue valueName not string:"+typeof k);l=a.pop();g=l instanceof c.Document;if(0==("c.Document"===typeof l||g))throw Error("GetDocumentValue document not document:"+typeof l);g=l.J(k);a.push(g);break;case c.c.h.fd:g=a.pop();k=a.pop();l=a.pop();l.P(k,g);break;case c.c.h.Sc:k=a.pop();g=a.pop();l=g[k];a.push(l);break;case c.c.h.gd:k=a.pop();g=a.pop();l=a.pop();l[k]=g;a.push(l);break;case c.c.h.$c:k=a.pop();g=a.pop();l=k in g;a.push(l);
break;case c.c.h.Zc:k=a.pop();l=a.pop();l[k]=0;a.push(l);break;case c.c.h.ad:k=a.pop();l=a.pop();delete l[k];a.push(l);break;case c.c.h.bd:var g=a.pop(),p;for(p in g)g.hasOwnProperty(p)&&(a.push(g[p]),a.push(p));break;case c.c.h.ld:for(l={};1<a.length;)k=a.pop(),g=a.pop(),l[k]=g;a.push(l);break;case c.c.h.Hc:g=a.pop();k=a.length-1-g;l=a[k];a.push(l);break;case c.c.h.ed:g=a.pop();k=a.length-1-g;a.splice(k,1);break;case c.c.h.Uc:k=a.pop();g=a.pop();l=a.pop();a.push(k?g:l);break;case c.c.h.Vc:g=a.pop();
!0===g&&(f=!1);break;case c.c.h.md:g=a.pop();l=void 0===g;a.push(l);break;case c.c.h.Gc:a.length=0;break;case c.c.h.Ic:g=a.pop();l=a.pop();l=g==l;a.push(l);break;case c.c.h.Xc:g=a.pop();l=a.pop();l=g<=l;a.push(l);break;case c.c.h.Wc:g=a.pop();l=a.pop();l=g<l;a.push(l);break;case c.c.h.Ec:g=a.pop();l=a.pop();l=g&&l;a.push(l);break;case c.c.h.cd:g=a.pop();l=a.pop();l=g||l;a.push(l);break;case c.c.h.Yc:g=a.pop();l=!g;a.push(l);break;case c.c.h.Fc:for(g=a.pop();0<g.length;)a.push(g.pop());break;case c.c.h.kd:for(g=
[];0<a.length;)g.push(a.pop());a.push(g);break;case c.c.h.hd:for(l=!0;0<a.length;)k=a.pop(),l=l&&k;a.push(l);break;case c.c.h.jd:for(l=!1;0<a.length;)if(k=a.pop(),!0===k){l=!0;a.length=0;break}a.push(l);break;case c.c.h.Jc:k=k[c.c.L];k=e[k];g=k();a.push(g);break;case c.c.h.Kc:g=a.pop();k=k[c.c.L];k=e[k];g=k(g);a.push(g);break;case c.c.h.Lc:g=a.pop();l=a.pop();k=k[c.c.L];k=e[k];g=k(g,l);a.push(g);break;case c.c.h.Mc:var g=a.pop(),l=a.pop(),n=a.pop(),k=k[c.c.L],k=e[k],g=k(g,l,n);a.push(g);break;case c.c.h.Nc:var g=
a.pop(),l=a.pop(),n=a.pop(),q=a.pop(),k=k[c.c.L],k=e[k],g=k(g,l,n,q);a.push(g);break;case c.c.h.Oc:var g=a.pop(),l=a.pop(),n=a.pop(),q=a.pop(),r=a.pop(),k=k[c.c.L],k=e[k],g=k(g,l,n,q,r);a.push(g);break;case c.c.h.Pc:var g=a.pop(),l=a.pop(),n=a.pop(),q=a.pop(),r=a.pop(),t=a.pop(),k=k[c.c.L],k=e[k],g=k(g,l,n,q,r,t);a.push(g);break;case c.c.h.Qc:var g=a.pop(),l=a.pop(),n=a.pop(),q=a.pop(),r=a.pop(),t=a.pop(),u=a.pop(),k=k[c.c.L],k=e[k],g=k(g,l,n,q,r,t,u);a.push(g)}}if(1!=a.length)throw Error("invalid calculation stack:"+
a.length+" "+JSON.stringify(a));return a[0]};c.A=function(a,b,d,e,f){this.w=a;this.Ba=b;this.Ra=e;this.N=d;this.qd=f;this.I=void 0;this.f=[];this.l=!0;this.Ya=[]};c.DagNodeCalculate=c.A;c.A.G=function(a,b,d,e,f){return new c.A(a,b,d,e,f)};c.A.Factory=c.A.G;c.A.prototype.S=function(){return this.w};c.A.prototype.GetName=c.A.prototype.S;
c.A.prototype.J=function(){c.D(!1,"DagNodeCalculate.GetValue dirty:"+this.l+" name:"+this.w);if(1==this.l){this.l=!1;try{this.I=c.cb.Jb(this.Ya,this.N,this.Ra,this.qd)}catch(a){c.D(!0,"SWALLOWING EXCEPTION: GetValue name:"+this.w+" threw error:"+a+" this:"+this),this.I=void 0}}return this.I};c.A.prototype.GetValue=c.A.prototype.J;c.A.prototype.$=function(){return this.l};c.A.prototype.GetDirty=c.A.prototype.$;
c.A.prototype.O=function(){if(1!=this.l){this.l=!0;for(var a=0,b=this.f.length;a<b;a++){var d=this.f[a];null!=d&&d.O()}a=this.Ba;a.f&&a.f.O()}};c.A.prototype.U=function(a){this.f.push(a)};c.A.prototype.aa=function(a){this.f=this.f.filter(function(b){return b!==a})};
c.A.prototype.toString=function(){for(var a="{m_name:"+this.w+", m_value:"+this.I+", m_dirty:"+this.l+", m_outputArray:[",b=0,d=this.f.length;b<d;b++){var e=this.f[b];b&&(a+=", ");a+=e.S()}a+="], m_instructionArray:[";b=0;for(d=this.N.length;b<d;b++)e=this.N[b],b&&(a+=", "),a+="{op:"+e[c.c.ba]+",value:"+e[c.c.L]+"}";return a+"]}"};c.A.prototype.toString=c.A.prototype.toString;c.b={};c.b.xb="clientlocked";c.b.B="type";c.b.g={ma:"bool",na:"boolarray",va:"int",wa:"intarray",qa:"float",ra:"floatarray",za:"string",Aa:"stringarray",xa:"key",ya:"keyarray",oa:"document",pa:"documentarray",ua:"iddocumentmap",sa:"hashset",ta:"hashsetarray"};c.b.ca="defaultvaluebool";c.b.Ea="defaultvalueint";c.b.Ta="defaultvalueintdatenow";c.b.ea="defaultvaluefloat";c.b.ga="defaultvaluestring";c.b.zb="defaultvaluestringrandid";c.b.yb="defaultvaluestringranddatabaseid";c.b.Fa="defaultvaluekey";
c.b.fa="defaultvaluekeyuserand";c.b.Ua="defaultvaluekeyrandarray";c.b.da="defaultvaluedocumenttype";c.b.Da="defaultvaluehashset";c.b.W="keypath";c.b.ha="documenttypearray";c.b.C="arraylengthmin";c.b.F="arraylengthmax";c.b.Gb="stringlengthmin";c.b.Fb="stringlengthmax";c.b.Eb="intrangelow";c.b.Db="intrangehigh";c.b.Cb="floatrangelow";c.b.Bb="floatrangehigh";c.a={};c.DagNodeValueHelper=c.a;
c.a.gb=function(a,b,d,e,f){switch(b[c.b.B]){case c.b.g.ma:return c.a.Nb(a,b);case c.b.g.na:return c.a.Ia(a,b);case c.b.g.va:return c.a.Tb(a,b);case c.b.g.wa:return c.a.La(a,b);case c.b.g.qa:return c.a.Qb(a,b);case c.b.g.ra:return c.a.Ja(a,b);case c.b.g.za:return c.a.Vb(a,b);case c.b.g.Aa:return c.a.Na(a,b);case c.b.g.xa:return c.a.Ub(a,b,d);case c.b.g.ya:return c.a.Ma(a,b,d);case c.b.g.oa:return c.a.Ob(a,b,e,f);case c.b.g.pa:return c.a.Pb(a,b,e,f);case c.b.g.ua:return c.a.Sb(a,b,e,f);case c.b.g.sa:return c.a.Rb(a,
b);case c.b.g.ta:return c.a.ib(a,b)}};c.a.FactoryValue=c.a.gb;c.a.Z=function(a,b,d,e){if(void 0!==d&&a.length<d)for(;a.length<d;)a.push(b);void 0!==e&&e<a.length&&(a.length=e)};c.a.M=function(a,b,d,e){if(void 0!==d&&a.length<d)for(;a.length<d;)a.push(b());void 0!==e&&e<a.length&&(a.length=e)};c.a.T=function(a){return function(){return(" "+a).slice(1)}};c.a.tb=function(a){return function(){return a[Math.floor(Math.random()*a.length)]}};c.a.mc=function(){return function(){return c.a.Pa()}};c.a.lc=function(){return function(){return c.a.Oa()}};
c.a.Nb=function(a,b){var d=b[c.b.ca];return!0===a?!0:!1===a?!1:void 0!==d?d:!1};c.a.Ia=function(a,b){var d=b[c.b.ca],e;if(void 0!=a&&Array.isArray(a)){e=a;for(var f=0,h=e.length;f<h;f++)e[f]=!0===e[f]}else e=[];c.a.Z(e,void 0!==d?d:!1,b[c.b.C],b[c.b.F]);return e};c.a.Tb=function(a,b){var d=b[c.b.Ea],d=void 0!==d?d:0;!0===b[c.b.Ta]&&(d=(new Date).valueOf());return c.a.jb(a,d,b[c.b.Eb],b[c.b.Db])};
c.a.jb=function(a,b,d,e){a="number"===typeof a?Math.round(a):b;void 0!==d&&(a=Math.max(d,a));void 0!==e&&(a=Math.min(e,a));return a};c.a.La=function(a,b){var d=b[c.b.Ea],d=void 0!==d?d:0;!0===b[c.b.Ta]&&(d=(new Date).valueOf());var e=b[c.b.Eb],f=b[c.b.Db],h;if(void 0!=a&&Array.isArray(a)){h=a;for(var m=0,k=h.length;m<k;m++){var g=h[m],g=c.a.jb(g,d,e,f);h[m]=g}}else h=[];c.a.Z(h,d,b[c.b.C],b[c.b.F]);return h};
c.a.hb=function(a,b,d,e){a="number"===typeof a?a:b;void 0!==d&&(a=Math.max(d,a));void 0!==e&&(a=Math.min(e,a));return a};c.a.Qb=function(a,b){var d=b[c.b.ea];return c.a.hb(a,void 0!==d?d:0,b[c.b.Cb],b[c.b.Bb])};c.a.Ja=function(a,b){var d=b[c.b.ea],d=void 0!==d?d:0,e=b[c.b.Cb],f=b[c.b.Bb],h;if(void 0!=a&&Array.isArray(a)){h=a;for(var m=0,k=h.length;m<k;m++){var g=h[m],g=c.a.hb(g,d,e,f);h[m]=g}}else h=[];c.a.Z(h,d,b[c.b.C],b[c.b.F]);return h};
c.a.lb=function(a,b,d,e){var f=void 0;"string"===typeof a||a instanceof String?f=a:f=b;if(void 0!==d&&f.length<d)for(;f.length<d;)f+="_";void 0!==e&&e<f.length&&(f=f.substr(0,e));return f};c.a.Vb=function(a,b){var d=b[c.b.ga],d=void 0!==d?d:"";!0===b[c.b.zb]&&(d=c.a.Pa());!0===b[c.b.yb]&&(d=c.a.Oa());return c.a.lb(a,d,b[c.b.Gb],b[c.b.Fb])};
c.a.Na=function(a,b){var d=b[c.b.ga],d=void 0!==d?d:"",e=b[c.b.Gb],f=b[c.b.Fb],h;if(void 0!=a&&Array.isArray(a)){h=a;for(var m=0,k=h.length;m<k;m++){var g=h[m],g=c.a.lb(g,d,e,f);h[m]=g}}else h=[];e=b[c.b.C];f=b[c.b.F];d=c.a.T(d);!0===b[c.b.zb]&&(d=c.a.mc);!0===b[c.b.yb]&&(d=c.a.lc);c.a.M(h,d,e,f);return h};c.a.kb=function(a,b,d,e,f){return("string"===typeof a||a instanceof String)&&e&&a in e?a:!0===d&&f?f[Math.floor(Math.random()*f.length)]:b};
c.a.Ub=function(a,b,d){d=c.K(d,b[c.b.W]);var e=b[c.b.Fa],f=b[c.b.fa];b=b[c.b.Ua];var h=[];if(d)for(temp_key in d)d.hasOwnProperty(temp_key)&&h.push(temp_key);void 0!==b&&(h=b);void 0==e&&(0<h.length?e=h[0]:e="");return c.a.kb(a,e,f,d,h)};
c.a.Ma=function(a,b,d){d=c.K(d,b[c.b.W]);var e=b[c.b.Fa],f=b[c.b.fa],h=b[c.b.Ua],m=[];if(d)for(temp_key in d)d.hasOwnProperty(temp_key)&&m.push(temp_key);void 0!==h&&(m=h);void 0==e&&(0<m.length?e=m[0]:e="");if(void 0!=a&&Array.isArray(a))for(var h=[],k=0,g=a.length;k<g;k++)innerResult=c.a.kb(a[k],e,f,d,m),h[k]=innerResult;else h=[];c.a.M(h,!0===f&&0<m.length?c.a.tb(m):c.a.T(e),b[c.b.C],b[c.b.F]);return h};c.a.Pa=function(){return c.Qa(16,"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")};
c.a.Oa=function(){return c.Qa(24,"0123456789ABCDEF")};c.a.la=function(a,b,d,e,f){if(e){var h=null,m=void 0;null!==a&&"object"===typeof a&&(m=e.l(a,f));m&&void 0!==d&&(h=m.w(),-1===d.indexOf(h)&&(m=void 0));if(!m){if(void 0===b)return;a=e.I(b);m=e.l(a,f)}m||c.D(!0,"c.DagNodeValueHelper.FactoryValueDocumentClean could not find type:"+h+" defaultType:"+b,!0);return m}};
c.a.Ob=function(a,b,d,e){if(!d)return null;var f=b[c.b.da];b=b[c.b.ha];void 0===f&&void 0!==b&&0<b.length&&(f=b[0]);return c.a.la(a,f,b,d,e)};c.a.Pb=function(a,b,d,e){var f=b[c.b.da],h=b[c.b.ha];void 0===f&&void 0!==h&&0<h.length&&(f=h[0]);if(void 0!=a&&Array.isArray(a)){for(var m=[],k=0,g=a.length;k<g;k++){var l=a[k];(l=c.a.la(l,f,h,d,e))&&m.push(l)}a=m}else a=[];c.a.M(a,c.a.kc(f,d,e),b[c.b.C],b[c.b.F]);return a};
c.a.Sb=function(a,b,d,e){b=b[c.b.ha];var f;if(void 0!=a&&Array.isArray(a)){f={};for(var h=0,m=a.length;h<m;h++){var k=c.a.la(a[h],void 0,b,d,e);if(k){var g=k.J(c.V.od);void 0!==g&&(f[g]=k)}}}else f={};return f};c.a.kc=function(a,b,d){return function(){var e=b.I(a);return b.l(e,d)}};c.a.Ka=function(a,b){var d={};if(void 0===a||!1===Array.isArray(a))a=b;if(void 0!=a&&Array.isArray(a))for(var e=0,f=a.length;e<f;e++){var h=a[e];if("string"===typeof h||h instanceof String)d[h]=0}return d};
c.a.Rb=function(a,b){return c.a.Ka(a,b[c.b.Da])};c.a.ib=function(a,b){var d=b[c.b.Da],e;if(void 0!=a&&Array.isArray(a)){e=[];for(var f=0,h=a.length;f<h;f++){var m=a[f],m=c.a.Ka(m,d);e[f]=m}}else e=[];c.a.M(e,c.a.sb(d),b[c.b.C],b[c.b.F]);return e};c.a.sb=function(a){return function(){return c.a.Ka(void 0,a)}};
c.a.nb=function(a,b,d,e){var f=a[c.b.B];switch(f){case c.b.g.ma:return c.a.Xb(a);case c.b.g.na:return c.a.Yb(a);case c.b.g.va:return c.a.qb(a);case c.b.g.wa:return c.a.gc(a);case c.b.g.qa:return c.a.bc(a);case c.b.g.ra:return c.a.cc(a);case c.b.g.za:return c.a.ic(a);case c.b.g.Aa:return c.a.jc(a);case c.b.g.xa:return c.a.rb(a,b);case c.b.g.ya:return c.a.hc(a,b);case c.b.g.oa:return c.a.ob(a,d,e);case c.b.g.pa:return c.a.ac(a,d,e);case c.b.g.ua:return c.a.fc();case c.b.g.sa:return c.a.pb(a);case c.b.g.ta:return c.a.dc(a)}c.D(!0,
"c.DagNodeValueHelper.MakeClearFunction type not found:"+f,!0);return function(){c.D(!0,"c.DagNodeValueHelper.MakeClearFunction type not found:"+f,!0)}};c.a.MakeClearFunction=c.a.nb;c.a.Xb=function(a){var b=a[c.b.ca],b=void 0!==b?b:!1;return function(){return b}};c.a.Yb=function(a){var b=a[c.b.ca],b=void 0!==b?b:!1,d=a[c.b.C],e=a[c.b.F];return function(){var a=[];c.a.Z(a,b,d,e);return a}};
c.a.qb=function(a){var b=a[c.b.Ea],b=void 0!==b?b:0,d=a[c.b.Ta];return function(){return!0===d?(new Date).valueOf():b}};c.a.gc=function(a){var b=c.a.qb(a),d=a[c.b.C],e=a[c.b.F];return function(){var a=[];c.a.M(a,b,d,e);return a}};c.a.bc=function(a){var b=a[c.b.ea],b=void 0!==b?b:0;return function(){return b}};c.a.cc=function(a){var b=a[c.b.ea],b=void 0!==b?b:0,d=a[c.b.C],e=a[c.b.F];return function(){var a=[];c.a.Z(a,b,d,e);return a}};c.a.ic=function(a){a=a[c.b.ga];return c.a.T(void 0!==a?a:"")};
c.a.jc=function(a){var b=a[c.b.ga],d=a[c.b.C],e=a[c.b.F],f=c.a.T(void 0!==b?b:"");return function(){var a=[];c.a.M(a,f,d,e);return a}};c.a.rb=function(a,b){var d=c.K(b,a[c.b.W]),e=a[c.b.Fa],f=a[c.b.fa],h=a[c.b.Ua],m=[];if(d)for(temp_key in d)d.hasOwnProperty(temp_key)&&m.push(temp_key);void 0!==h&&(m=h);void 0==e&&(0<m.length?e=m[0]:e="");return!0===f&&0<m.length?c.a.tb(m):c.a.T(e)};c.a.hc=function(a,b){var d=c.a.rb(a,b),e=a[c.b.C],f=a[c.b.F];return function(){var a=[];c.a.M(a,d,e,f);return a}};
c.a.$b=function(a){var b=a[c.b.Ad];a=a[c.b.Bd];b=void 0!==b?b:0;return!0===a?function(){return new Date}:function(){return new Date(b)}};c.a.ud=function(a){var b=c.a.$b(a),d=a[c.b.C],e=a[c.b.F];return function(){var a=[];c.a.M(a,b,d,e);return a}};c.a.ec=function(a){var b=a[c.b.Cd];return!0===a[c.b.Dd]?function(){return c.a.Pa()}:c.a.T(void 0!==b?b:"")};c.a.vd=function(a){var b=c.a.ec(a),d=a[c.b.C],e=a[c.b.F];return function(){var a=[];c.a.M(a,b,d,e);return a}};
c.a.Zb=function(a){var b=a[c.b.yd];return!0===a[c.b.zd]?function(){return c.a.Oa()}:c.a.T(void 0!==b?b:"")};c.a.td=function(a){var b=c.a.Zb(a),d=a[c.b.C],e=a[c.b.F];return function(){var a=[];c.a.M(a,b,d,e);return a}};c.a.ob=function(a,b,d){var e=a[c.b.da],f=a[c.b.ha];return function(){c.a.la(void 0,e,f,b,d)}};c.a.ac=function(a,b,d){var e=c.a.ob(a,b,d),f=a[c.b.C],h=a[c.b.F];return function(){var a=[];c.a.M(a,e,f,h);return a}};c.a.fc=function(){return function(){return{}}};c.a.pb=function(a){return c.a.sb(a[c.b.Da])};
c.a.dc=function(a){var b=c.a.pb(a),d=a[c.b.C],e=a[c.b.F];return function(){var a=[];c.a.M(a,b,d,e);return a}};
c.a.nc=function(a,b,d,e){switch(b[c.b.B]){case c.b.g.ma:return c.a.oc(a,b);case c.b.g.na:return c.a.pc(a,b);case c.b.g.va:return c.a.xc(a,b);case c.b.g.wa:return c.a.yc(a,b);case c.b.g.qa:return c.a.sc(a,b);case c.b.g.ra:return c.a.tc(a,b);case c.b.g.za:return c.a.Bc(a,b);case c.b.g.Aa:return c.a.Cc(a,b);case c.b.g.xa:return c.a.zc(a,b,d);case c.b.g.ya:return c.a.Ac(a,b,d);case c.b.g.oa:return c.a.qc(a,b,e);case c.b.g.pa:return c.a.rc(a,b,e);case c.b.g.ua:return c.a.wc(a,e);case c.b.g.sa:return c.a.uc(a,
b);case c.b.g.ta:return c.a.vc(a,b)}};c.a.oc=function(a,b){var d=b[c.b.ca];void 0===d&&(d=!1);if(!0===a&&a!==d||!1===a&&a!==d)return a};c.a.pc=function(a,b){var d=c.a.Ia(a,b),e=c.a.Ia(void 0,b);if(!0!==c.a.Y(d,e))return d};c.a.xc=function(a,b){var d=b[c.b.Ea];if("number"===typeof a){var e=Math.round(a);if(e!==(void 0!==d?d:0))return e}};c.a.yc=function(a,b){var d=c.a.La(a,b),e=c.a.La(void 0,b);if(!0!==c.a.Y(d,e))return d};
c.a.sc=function(a,b){var d=b[c.b.ea];if("number"===typeof a&&a!==(void 0!==d?d:0))return a};c.a.tc=function(a,b){var d=c.a.Ja(a,b),e=c.a.Ja(void 0,b);if(!0!==c.a.Y(d,e))return d};c.a.Bc=function(a,b){var d=b[c.b.ga];if(("string"===typeof a||a instanceof String)&&(void 0!==d?d:"")!==a)return a};c.a.Cc=function(a,b){var d=c.a.Na(a,b),e=c.a.Na(void 0,b);if(!0!==c.a.Y(d,e))return d};
c.a.zc=function(a,b,d){d=c.K(d,b[c.b.W]);var e=b[c.b.Fa];!0===b[c.b.fa]&&(e=void 0);if(d&&("string"===typeof a||a instanceof String)&&a in d&&a!==e)return a};c.a.Ac=function(a,b,d){a=c.a.Ma(a,b,d);if(1==b[c.b.fa])return a;b=c.a.Ma(void 0,b,d);if(!0!==c.a.Y(a,b))return a};c.a.qc=function(a,b,d){var e=b[c.b.ha],f=void 0;"GetType"in a&&(f=a.GetType());var h=void 0;void 0!==e&&void 0!==f&&-1!==e.indexOf(f)&&(h=d.w(a));if(h&&(f!==b[c.b.da]||1!==Object.keys(h).length))return h};
c.a.rc=function(a,b,d){if(void 0!=a&&!1!==Array.isArray(a)){var e=[],f=b[c.b.da];b=b[c.b.C];void 0===b&&(b=0);b=1&a.length==b;for(var h=0,m=a.length;h<m;h++){var k=d.w(a[h]);b&=k.type===f&&1===Object.keys(k).length;e.push(k)}if(1!=b)return e}};c.a.wc=function(a,b){if(void 0!=a){var d=0,e=[];for(id in a)if(a.hasOwnProperty(id)){var f=a[id];void 0!=f&&"GetValue"in f&&f.J("id")===id&&(f=b.w(f),e.push(f),d+=1)}if(d)return e}};
c.a.Y=function(a,b){var d=void 0!=b&&Array.isArray(b);if(0==(void 0!=a&&Array.isArray(a))||0==d||a.length!=b.length)return!1;for(var d=0,e=a.length;d<e;d++)if(a[d]!==b[d])return!1;return!0};c.a.rd=function(a,b){var d=void 0!=b&&Array.isArray(b);if(0==(void 0!=a&&Array.isArray(a))||0==d||a.length!=b.length)return!1;for(var d=0,e=a.length;d<e;d++)if(a[d].valueOf()!==b[d].valueOf())return!1;return!0};
c.a.$a=function(a,b){var d=void 0!=b&&Array.isArray(b);if(0==(void 0!=a&&Array.isArray(a))||0==d||a.length!=b.length)return!1;for(var d=0,e=a.length;d<e;d++)if(-1===b.indexOf(a[d]))return!1;return!0};c.a.uc=function(a,b){var d=b[c.b.Da];void 0===d&&(d=[]);var e;if(void 0!==a){e=[];for(temp_key in a)a.hasOwnProperty(temp_key)&&e.push(temp_key);if(!1===c.a.$a(e,d))return e}};
c.a.vc=function(a,b){if(void 0!=a&&!1!==Array.isArray(a)){for(var d=[],e=1,f=c.a.ib(void 0,b),e=e&a.length===f.length,h=0,m=a.length;h<m;h++){var k=a[h],g=f[h],l=void 0!=g?Object.keys(g):[],p=[];for(temp_key in k)k.hasOwnProperty(temp_key)&&p.push(temp_key);e&=void 0!=g&&1==c.a.$a(p,l);d.push(p)}if(1!=e)return d}};c.i=function(a,b,d,e){this.I=a;this.N=b;this.w=d;this.Ba=e;this.f=[];this.l=[]};c.DagNodeValue=c.i;c.i.G=function(a,b,d,e){return new c.i(a,b,d,e)};c.i.Factory=c.i.G;c.i.prototype.ab=function(){var a=this.Ba();a!==this.w&&(this.w=a,this.O())};c.i.prototype.Clear=c.i.prototype.ab;c.i.prototype.J=function(){c.D(!1,"DagNodeValue.GetValue name:"+this.I);return this.w};c.i.prototype.GetValue=c.i.prototype.J;
c.i.prototype.P=function(a){if(a===this.w)return!1;for(var b=0,d=this.l.length;b<d;b++){var e=this.l[b];void 0!==e&&e.ab()}this.w=a;this.O();return!0};c.i.prototype.SetValue=c.i.prototype.P;c.i.prototype.O=function(){for(var a=0,b=this.f.length;a<b;a++){var d=this.f[a];void 0!==d&&d.O()}this.N&&(a=this.N,a.f&&a.f.O())};c.i.prototype.SetDirty=c.i.prototype.O;c.i.prototype.S=function(){return this.I};c.i.prototype.GetName=c.i.prototype.S;c.i.prototype.U=function(a){this.f.push(a)};
c.i.prototype.AddOutput=c.i.prototype.U;c.i.prototype.aa=function(a){this.f=this.f.filter(function(b){return b!==a})};c.i.prototype.RemoveOutput=c.i.prototype.aa;c.i.prototype.Ra=function(a){this.l.push(a)};c.i.prototype.AddExclusive=c.i.prototype.Ra;c.i.prototype.Ya=function(a){this.l=this.l.filter(function(b){return b!==a})};c.i.prototype.RemoveExclusive=c.i.prototype.Ya;
c.i.prototype.toString=function(){for(var a="{m_name:"+this.I+", m_value:"+this.w+", m_outputArray:[",b=0,d=this.f.length;b<d;b++){var e=this.f[b];b&&(a+=", ");a+=e.S()}a+="], m_exclusiveArray[";b=0;for(d=this.l.length;b<d;b++)e=this.l[b],b&&(a+=", "),a+=e.S();return a+"]}"};c.i.prototype.toString=c.i.prototype.toString;c.eb={};c.eb.Ib=function(a,b){for(var d=0,e=b.length;d<e;d++)for(var f=b[d],h=f.N,m=0,k=h.length;m<k;m++){var g=h[m],l=g[c.c.ba],p=c.c.h.vb===l,l=c.c.h.wb===l;if(!1!==p||!1!==l){var n=g[c.c.L],q=a[n];if(!q)throw Error("AddNodeMapLinks node not found:"+n);g[c.c.Sa]=q;!0===p&&c.u.f(q,f);if(!0===l){if(!1===q instanceof c.i)throw Error("AddNodeMapLinks node incorrect type for setNode:"+n);c.u.f(f,q)}}}};c.u=function(a){this.f=a};c.DagNodeCollection=c.u;c.u.G=function(a){return new c.u(a)};c.u.Factory=c.u.G;c.u.prototype.J=function(a){c.D(!1,"DagNodeCollection.GetValue in_name:"+a+" in:"+(a in this.f));if(a in this.f)return this.f[a].J()};c.u.prototype.GetValue=c.u.prototype.J;c.u.prototype.P=function(a,b){a in this.f&&this.f[a].P(b)};c.u.prototype.SetValue=c.u.prototype.P;c.u.prototype.w=function(a){c.D(!0,"DagNodeCollection.GetNode in_name:"+a);if(a in this.f)return this.f[a]};
c.u.prototype.GetNode=c.u.prototype.w;c.u.prototype.l=function(a,b){this.f[a]=b};c.u.prototype.SetNode=c.u.prototype.l;c.u.f=function(a,b){a?b?(a.U(b),b.O()):c.D(!0,"c.DagNodeCollection.SetNodesLinked in_output:"+b):c.D(!0,"c.DagNodeCollection.SetNodesLinked in_input:"+a)};c.u.SetNodesLinked=c.u.f;c.u.l=function(a,b){a.aa(b);b.O()};c.u.SetNodesUnlinked=c.u.l;
c.u.prototype.toString=function(){var a="{m_mapNameNode:{",b=!0,d;for(d in this.f)!0===b?b=!1:a+=", ",a+=d+":"+this.f[d].toString();return a+"}}"};c.V={};c.V.B="type";c.V.od="id";c.Document=function(a,b,d){this.I=a;this.l=b;this.f=d};c.Document=c.Document;c.Document.G=function(a,b,d){return new c.Document(a,b,d)};c.Document.Factory=c.Document.G;c.Document.prototype.w=function(){return this.I};c.Document.prototype.GetType=c.Document.prototype.w;c.Document.prototype.J=function(a){c.D(!1,"c.Document.GetValue name:"+a);return this.l.J(a)};c.Document.prototype.GetValue=c.Document.prototype.J;c.Document.prototype.P=function(a,b){!0===this.l.P(a,b)&&null!==this.f&&this.f.O()};
c.Document.prototype.SetValue=c.Document.prototype.P;c.Document.prototype.U=function(){var a=this.l,b=[],d;for(d in a.f)b.push(d);return b};c.Document.prototype.GetPropertyNameArray=c.Document.prototype.U;c.Document.prototype.N=function(){var a=this.l,b=[],d;for(d in a.f){var e=a.f[d];e.$&&!0===e.$()&&b.push(d)}return b};c.Document.prototype.GetDirtyArray=c.Document.prototype.N;
c.Document.prototype.toString=function(){var a="{m_type:"+this.I+",";this.f&&(a+="m_parentNode:"+this.f.S()+",");a+="m_dagCollection:"+this.l+"}";return a+"}"};c.v=function(a,b){this.f=a;this.N=b};c.DocumentManager=c.v;c.v.G=function(a,b){return new c.v(a,b)};c.v.Factory=c.v.G;c.v.prototype.I=function(a){if(null==this.f[c.H.ia])c.D(!0,"DocumentManager.NewDocumentData gameobject_types undefined");else if(!1===a in this.f[c.H.ia])c.D(!0,"DocumentManager.NewDocumentData document_types in_type not found:"+a);else{var b={};b[c.V.B]=a;a=this.l(b,void 0);b=void 0;a&&(b=this.w(a));return b}};c.v.prototype.NewDocumentData=c.v.prototype.I;
c.v.prototype.$=function(a,b){var d=this.f[c.H.ia][a];if(null!=d){var e=c.K(this.f,d[c.H.Va]),e=e&&b in e?e[b]:void 0,f=(d=c.K(this.f,d[c.H.Ab]))&&b in d?d[b]:void 0,h=d=void 0,m=void 0;void 0!==e&&c.b.B in e&&(d=e[c.b.B]);void 0!==f&&c.c.B in f&&(d=f[c.c.B]);void 0!==e&&(h=c.b.xb in e?!0===e[c.b.xb]:!1);void 0!==f&&(h=!0);void 0!==e&&c.b.W in e&&(e=c.K(this.f,e[c.b.W]))&&(m=Object.keys(e));return{type:d,locked:h,keyoptions:m}}};c.v.prototype.GetDocumentPropertyData=c.v.prototype.$;
c.v.prototype.l=function(a,b){if(a){var d=a[c.V.B];if(null==d)c.D(!0,"DocumentManager.DocumentDataToDocument no type in data document");else{var e=this.f[c.H.ia][d];if(null!=e){var f=c.u.G({}),d=c.Document.G(d,f,b),h=c.K(this.f,e[c.H.Va]),m=c.K(this.f,e[c.H.Ab]),k=e[c.H.nd],e={};void 0!=k&&this.N&&(e=this.N[k]);e=void 0===e?{}:e;if(h)for(var g in h){var l=h[g],k=c.i.G(g,d,void 0,void 0),p=c.a.nb(l,this.f,this,k),l=c.a.gb(a[g],l,this.f,this,k);k.P(l);k.Ba=p;f.l(g,k)}g=[];if(m)for(var n in m){h=m[n][c.c.Ca];
k=[];p=0;for(l=h.length;p<l;p++){var q=h[p],r={};r[c.c.ba]=q[c.c.ba];r[c.c.L]=q[c.c.L];k.push(r)}h=c.A.G(n,d,k,this.f,e);g.push(h);f.l(n,h)}c.eb.Ib(f.f,g);return d}}}};c.v.prototype.DocumentDataToDocument=c.v.prototype.l;c.v.prototype.w=function(a){if(a){var b=a.w(),d=this.f[c.H.ia][b];if(null!=d){var d=c.K(this.f,d[c.H.Va]),e={};e[c.V.B]=b;if(d)for(var f in d){var b=d[f],h=a.J(f);void 0!==h&&(b=c.a.nc(h,b,this.f,this),void 0!==b&&(e[f]=b))}return e}}};c.v.prototype.DocumentToDocumentData=c.v.prototype.w;
c.v.prototype.aa=function(a,b,d,e){return c.o.G(a,b,d,e)};c.v.prototype.MakeUpdatePatch=c.v.prototype.aa;c.v.prototype.U=function(a,b){return c.o.Za(a,b)};c.v.prototype.ApplyUpdatePatch=c.v.prototype.U;c.H={};c.H.ia="documenttypes";c.H.Va="value";c.H.Ab="calculate";c.H.nd="instructioncontext";c.j={};c.j.pd="lock";c.j.Ca="d";c.j.B="t";c.j.Xa="r";c.j.Wa="i";c.j.Hb="u";c.j.X="p";c.j.ja="v";c.o={};c.ObjectDelta=c.o;c.o.G=function(a,b,d,e){var f=[];e||(e=[]);c.o.bb(f,e,a,b);a={};0<f.length&&(a[c.j.Ca]=f);void 0!=d&&(a[c.j.pd]=d);return a};c.o.Factory=c.o.G;
c.o.Ga=function(a,b,d,e){if(void 0!==d&&void 0===e)e={},e[c.j.B]=c.j.Xa,e[c.j.X]=c.R(b),a.push(e);else if(void 0===d&&void 0!==e)d={},d[c.j.B]=c.j.Wa,d[c.j.X]=c.R(b),d[c.j.ja]=e,a.push(d);else if(void 0!==d&&void 0!==e){var f=Object.prototype.toString.call(d),h=Object.prototype.toString.call(e);f!==h?c.D(!0,"c.ObjectDelta.CollectDelta type missmatch sourceType:"+f+" targetType:"+h+" path:"+JSON.stringify(b)):"[object Array]"===f?c.o.Kb(a,b,d,e):"[object Object]"===f?c.o.bb(a,b,d,e):d!==e&&(d={},d[c.j.B]=
c.j.Hb,d[c.j.X]=c.R(b),d[c.j.ja]=e,a.push(d))}};c.o.Kb=function(a,b,d,e){for(var f=[],h=0,m=e.length;h<m;h++){for(var k=e[h],g=[],l=0,p=d.length;l<p;l++){var n=c.o.ka(d[l],k);0>=n||g.push({s:l,m:n})}f.push(g)}f=c.o.Dc(f);h=p=l=g=0;for(m=f.length;h<m;h++){k=e[h];n=f[h];if(void 0==n)c.o.Lb(a,b,k,h),g+=1;else{for(var q=n.s,r=q+g-l;h<r;)c.o.fb(a,b,r-1),l+=1,r=q+g-l;n=n.m;1>n&&c.o.Mb(a,b,d[q],k,r)}p+=1}for(;p<d.length+g-l;)c.o.fb(a,b,p),l+=1};
c.o.ka=function(a,b){var d=Object.prototype.toString.call(a);if(d!==Object.prototype.toString.call(b))return 0;if("[object Array]"===d){var d=0,e=1;a.length!==b.length&&(e=.5);for(var f=Math.min(a.length,b.length),h=0;h<f;h++)d+=c.o.ka(a[h],b[h]);h=1;0<f&&(h=d/f);return h*e}if("[object Object]"===d){d=f=0;for(key in a)!1!==a.hasOwnProperty(key)&&(f+=1,d+=c.o.ka(a[key],b[key]));for(key in b)!1===b.hasOwnProperty(key)||key in a||(f+=1,d+=c.o.ka(a[key],b[key]));h=1;0<f&&(h=d/f);return h}return a===b?
1:0};c.o.fb=function(a,b,d){var e={};b=c.R(b);b.push(d);e[c.j.B]=c.j.Xa;e[c.j.X]=b;a.push(e)};c.o.Lb=function(a,b,d,e){var f={};b=c.R(b);b.push(e);f[c.j.B]=c.j.Wa;f[c.j.X]=b;f[c.j.ja]=d;a.push(f)};c.o.Mb=function(a,b,d,e,f){b=c.R(b);b.push(f);c.o.Ga(a,b,d,e)};c.o.Dc=function(a){for(var b=[],d=-1,e=0,f=a.length;e<f;e++){for(var h=a[e],m=void 0,k=0,g=h.length;k<g;k++){var l=h[k];if(d<l.s){d=l.s;m=l;break}}b.push(m)}return b};
c.o.bb=function(a,b,d,e){for(key in d)if(!1!==d.hasOwnProperty(key)){var f=c.R(b);f.push(key);c.o.Ga(a,f,d[key],e[key])}for(key in e)!1===e.hasOwnProperty(key)||key in d||(f=c.R(b),f.push(key),c.o.Ga(a,f,d[key],e[key]))};
c.o.Za=function(a,b){var d=c.Ha(a),e=b[c.j.Ca];if(null==e)return d;for(var f=0,h=e.length;f<h;f++){var m=e[f],k=m[c.j.B],g=c.R(m[c.j.X]);switch(k){case c.j.Xa:m=g[g.length-1];g.splice(-1,1);g=c.K(d,g);!0===c.mb(g)?g.splice(m,1):delete g[m];break;case c.j.Wa:k=g[g.length-1];g.splice(-1,1);g=c.K(d,g);m=m[c.j.ja];!0===c.mb(g)?g.splice(k,0,m):g[k]=m;break;case c.j.Hb:m=m[c.j.ja],c.ub(d,g,m)}}return d};c.o.ApplyDelta=c.o.Za;c.Wb={};c.InstructionContext=c.Wb;
